# Generated by Django 3.1.7 on 2021-04-18 17:53

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutChildrenModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_first_table', models.CharField(blank=True, default='Nimadir', max_length=24, null=True, verbose_name='Birinchi jadvalning nomini kiriting ')),
                ('num_of_first_table', models.IntegerField(blank=True, default=0, null=True, validators=[main.models.check_condition], verbose_name='Birinchi jadvaldagi sonni kiriting ')),
                ('name_of_second_table', models.CharField(blank=True, default='Nimadir', max_length=24, null=True, verbose_name='Ikkinchi jadvalning nomini kiriting ')),
                ('num_of_second_table', models.IntegerField(blank=True, default=0, null=True, validators=[main.models.check_condition], verbose_name='Ikkinchi jadvalning sonni kiriting ')),
                ('name_of_third_table', models.CharField(blank=True, default='Nimadir', max_length=24, null=True, verbose_name='Uchinchi jadvalning nomini kiriting ')),
                ('num_of_third_table', models.IntegerField(blank=True, default=0, null=True, validators=[main.models.check_condition], verbose_name='Uchinchi jadvalning sonni kiriting ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kiritilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': "Shaxsiy ma'lumot",
                'verbose_name_plural': "Shaxsiy ma'lumot",
            },
        ),
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_main_title', models.CharField(max_length=48, null=True, verbose_name='Jadvalning nomi ')),
                ('banner_message_on_title', models.TextField(blank=True, max_length=216, null=True, verbose_name="Jadvaldagi ma'lumot")),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kiritilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': 'Banner modeli',
                'verbose_name_plural': 'Banner modeli',
            },
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(verbose_name='Manzil ')),
                ('email', models.EmailField(max_length=254, verbose_name='Email manzilingiz ')),
                ('contact_num', models.CharField(max_length=32, verbose_name='Kontakt raqam ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kiritilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': 'Kontakt',
                'verbose_name_plural': 'Kontakt',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ismi ')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Telefon-raqami ')),
                ('message', models.TextField(max_length=1500, verbose_name='Xabar ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kiritilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': 'Xabarlar',
                'verbose_name_plural': 'Xabarlar',
            },
        ),
        migrations.CreateModel(
            name='GalaryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', validators=[main.models.galary_photo_dimensions], verbose_name='Jadvalning rasmi ')),
                ('main_title', models.CharField(max_length=32, verbose_name='Jadvalning nomi ')),
                ('title', models.CharField(blank=True, max_length=32, null=True, verbose_name="Jadvaldagi ma'lumot ")),
                ('message', models.TextField(blank=True, null=True, verbose_name='Jadvaldagi habar ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kiritilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': 'Surat',
                'verbose_name_plural': 'Suratlar',
            },
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Rasmni 300x400 darajasida joylashtiring', upload_to='', validators=[main.models.news_photo_dimensions], verbose_name='Foto rasmi ')),
                ('title', models.CharField(max_length=45, verbose_name='Jadvalning nomi ')),
                ('message', models.TextField(verbose_name='Jadvaldagi habar ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kiritilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': 'Yangiliklar',
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=64, verbose_name='Ismi ')),
                ('title', models.CharField(max_length=64, verbose_name='Vazifasi ')),
                ('photo', models.ImageField(help_text="O'lcahmi 3x4 bo'lgan rasmni kiriting!", upload_to='Rasmni kiriting', validators=[main.models.staff_photo_dimensions], verbose_name='Foto rasmi ')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Ma"lumot ')),
                ('twitter', models.CharField(blank=True, max_length=200, null=True, verbose_name='Twitter linki (shart emas) ')),
                ('facebook', models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook linki (shart emas) ')),
                ('instagram', models.CharField(blank=True, max_length=200, null=True, verbose_name='Instagram linki (shart emas) ')),
                ('linkedin_box', models.CharField(blank=True, max_length=200, null=True, verbose_name='linkedin-box linki (shart emas) ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kiritilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': "Adminlar ma'lumoti",
                'verbose_name_plural': "Adminlar ma'lumoti",
            },
        ),
    ]
