# Generated by Django 3.1.7 on 2021-04-22 11:17

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutChildrenModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_first_table', models.CharField(blank=True, default='Nimadir', max_length=24, null=True, verbose_name='Jadvalning nomini kiriting ')),
                ('num_of_first_table', models.IntegerField(blank=True, default=0, null=True, validators=[main.models.check_condition], verbose_name='Jadvaldagi sonni kiriting ')),
                ('name_of_second_table', models.CharField(blank=True, default='Nimadir', max_length=24, null=True, verbose_name='Jadvalning nomini kiriting ')),
                ('num_of_second_table', models.IntegerField(blank=True, default=0, null=True, validators=[main.models.check_condition], verbose_name='Jadvalning sonni kiriting ')),
                ('name_of_third_table', models.CharField(blank=True, default='Nimadir', max_length=24, null=True, verbose_name='Jadvalning nomini kiriting ')),
                ('num_of_third_table', models.IntegerField(blank=True, default=0, null=True, validators=[main.models.check_condition], verbose_name='Jadvalning sonni kiriting ')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': "Statistik ma'lumotlar",
                'verbose_name_plural': "Statistik ma'lumotlar",
            },
        ),
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_main_title', models.CharField(max_length=48, null=True, verbose_name='Bannerning nomi ')),
                ('banner_message_on_title', models.TextField(blank=True, max_length=216, null=True, verbose_name="Bannerdagi ma'lumot")),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banner',
            },
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(verbose_name='Manzil ')),
                ('email', models.EmailField(max_length=254, verbose_name='Email manzilingiz ')),
                ('contact_num', models.CharField(max_length=32, verbose_name='Kontakt raqam ')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': 'Kontakt',
                'verbose_name_plural': 'Kontakt',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ismi ')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Telefon-raqami ')),
                ('message', models.TextField(max_length=1500, verbose_name='Xabar ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kiritilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': 'Xabarlar',
                'verbose_name_plural': 'Xabarlar',
            },
        ),
        migrations.CreateModel(
            name='GalaryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Gallereya', verbose_name='Gallereya rasmi ')),
                ('main_title', models.CharField(max_length=32, verbose_name='Gallereyadagi assosiy mavzu ')),
                ('title', models.CharField(blank=True, max_length=32, null=True, verbose_name='Gallereyadagi mavzu ')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Gallereyadagi habar ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kiritilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': 'Gallereya',
                'verbose_name_plural': 'Gallereya',
            },
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text="Nisbati 3x4 bo'lgan rasmni kiriting!", upload_to='Yangiliklar', verbose_name='Yangilikning rasmi ')),
                ('title', models.CharField(max_length=45, verbose_name='Yangilikning nomi ')),
                ('message', models.TextField(verbose_name='Yangilikdagi habar ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kiritilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': 'Yangiliklar',
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=64, verbose_name='Ismi ')),
                ('title', models.CharField(max_length=64, verbose_name='Vazifasi ')),
                ('photo', models.ImageField(help_text="Nisbati 3x4 bo'lgan rasmni kiriting!", upload_to='Staff', validators=[main.models.staff_photo_dimensions], verbose_name='Foto rasmi ')),
                ('info', models.TextField(blank=True, null=True, verbose_name="Ma'lumot")),
                ('twitter', models.CharField(blank=True, max_length=200, null=True, verbose_name='Twitter linki ')),
                ('facebook', models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook linki ')),
                ('instagram', models.CharField(blank=True, max_length=200, null=True, verbose_name='Instagram linki ')),
                ('linkedin_box', models.CharField(blank=True, max_length=200, null=True, verbose_name='linkedin-box linki ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kiritilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': 'Hodimlar',
                'verbose_name_plural': 'Hodimlar',
            },
        ),
    ]
