# Generated by Django 3.1.7 on 2021-04-18 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannermodel',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Banner'},
        ),
        migrations.RemoveField(
            model_name='aboutchildrenmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bannermodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='created_at',
        ),
    ]
