# Generated by Django 3.1.7 on 2021-04-18 18:10

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210418_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galarymodel',
            name='photo',
            field=models.ImageField(upload_to='Rasm kiritildi', validators=[main.models.galary_photo_dimensions], verbose_name='Jadvalning rasmi '),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='image',
            field=models.ImageField(help_text='Rasmni 300x400 darajasida joylashtiring', upload_to='Rasm kiritildi', validators=[main.models.news_photo_dimensions], verbose_name='Foto rasmi '),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='photo',
            field=models.ImageField(help_text="O'lcahmi 3x4 bo'lgan rasmni kiriting!", upload_to='Rasm kiritildi', validators=[main.models.staff_photo_dimensions], verbose_name='Foto rasmi '),
        ),
    ]
